# fly.toml app configuration file generated for blue-dust-2805 on 2023-10-09T15:33:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blue-dust-2805"
# https://fly.io/docs/reference/regions/ the other option was fra for frankfurt but lhr is closer to me
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[processes]
  app = ""

[[services]]
  protocol = "tcp"
  internal_port = 5000
  auto_stop_machines = true  # Automatically stop machines when idle
  auto_start_machines = true  # Automatically start machines based on demand
  min_machines_running = 0  # Keep zero machines running when idle
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1  # Set to 1 to minimize resource usage
    soft_limit = 1  # Set to 1 to minimize resource usage

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
